[tool.poetry]
name = "${PROJECT}"
description = "${DESCRIPTION}"
package-mode = false
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
pulumi = ">=3.0.0,<4.0.0"
pulumi-aws = ">=6.0.2,<7.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
